title: Fern's Notes
email: diazjf@us.ibm.com
description: >-
  I little info about programming, coffee, and some
  random tidbits. Everything I say is my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diazjf.github.io"
github_username:  diazjf

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
